version: '3.8'
services:
  postgres:
    image: postgres:latest
    volumes:
      - ./postgresql:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=loan_tracker_dev
    ports:
      - 5432:5432
    networks:
      - docker-compose-postgres-network

networks:
  docker-compose-postgres-network:
